# Generated by Django 4.2.7 on 2023-11-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cryptocurrency_experience",
                    models.IntegerField(
                        choices=[(1, "Novice"), (2, "Intermediate"), (3, "Advanced")],
                        default=1,
                    ),
                ),
                (
                    "platform_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "Not satisfied"),
                            (2, "Satisfied"),
                            (3, "Very satisfied"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "security_confidence",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Moderate"), (3, "High")], default=2
                    ),
                ),
                ("future_expectations", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "change_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("volume_24h", models.DecimalField(decimal_places=2, max_digits=20)),
                ("lasthour", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "volume_change_24h",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("last24h", models.DecimalField(decimal_places=2, max_digits=10)),
                ("week", models.DecimalField(decimal_places=2, max_digits=10)),
                ("month", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TwoMonths", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ThreeMonths", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
