# Generated by Django 4.2.7 on 2023-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
