# Generated by Django 4.2.7 on 2023-11-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
