# Generated by Django 4.2.7 on 2023-11-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0004_cryptocurrency"),
    ]

    operations = [
        migrations.DeleteModel(name="Cryptocurrency",),
        migrations.DeleteModel(name="StockData",),
    ]
