# Generated by Django 4.2.7 on 2023-11-27 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "CryptoWebsite",
            "0005_userprofile_phone_no_userprofile_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("quantity_purchased", models.IntegerField(default=1)),
                ("updated_quantity", models.IntegerField(default=0)),
                ("purchased_currency", models.CharField(default="CAD", max_length=3)),
                (
                    "purchase_price_per_unit",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "total_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "updated_total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("OL", "ONLINE"), ("CARD", "CARD")],
                        default="OL",
                        max_length=4,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("B", "BUY"), ("S", "SELL")],
                        default="B",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "ACTIVE"), ("I", "INACTIVE")],
                        default="A",
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-payment_date"],},
        ),
    ]
