# Generated by Django 4.2.7 on 2023-11-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0005_delete_cryptocurrency_delete_stockdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("symbol", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
