# Generated by Django 4.2.7 on 2023-11-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0006_paymenthistory"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.DeleteModel(name="Payment",),
        migrations.DeleteModel(name="UserProfile",),
    ]
