# Generated by Django 4.2.7 on 2023-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0006_stockdata"),
    ]

    operations = [
        migrations.RemoveField(model_name="stockdata", name="timestamp",),
        migrations.AddField(
            model_name="stockdata",
            name="change_percentage",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="market_cap",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="percent_change_1h",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="percent_change_24h",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="percent_change_30d",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="percent_change_60d",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="percent_change_7d",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="percent_change_90d",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="volume_24h",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="volume_change_24h",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="stockdata", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
