# Generated by Django 4.2.7 on 2023-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0007_remove_stockdata_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="change_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="market_cap",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="percent_change_1h",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="percent_change_24h",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="percent_change_30d",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="percent_change_60d",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="percent_change_7d",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="percent_change_90d",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="volume_24h",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="volume_change_24h",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
