# Generated by Django 4.2.7 on 2023-11-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0008_alter_stockdata_change_percentage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="percent_change_1h",
            new_name="ThreeMonths",
        ),
        migrations.RenameField(
            model_name="stockdata", old_name="percent_change_24h", new_name="TwoMonths",
        ),
        migrations.RenameField(
            model_name="stockdata", old_name="percent_change_30d", new_name="last24h",
        ),
        migrations.RenameField(
            model_name="stockdata", old_name="percent_change_60d", new_name="lasthour",
        ),
        migrations.RenameField(
            model_name="stockdata", old_name="percent_change_7d", new_name="month",
        ),
        migrations.RenameField(
            model_name="stockdata", old_name="percent_change_90d", new_name="week",
        ),
    ]
