# Generated by Django 4.2.7 on 2023-11-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoWebsite", "0010_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cryptocurrency_experience",
                    models.IntegerField(
                        choices=[(1, "Novice"), (2, "Intermediate"), (3, "Advanced")],
                        default=1,
                    ),
                ),
                (
                    "platform_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "Not satisfied"),
                            (2, "Satisfied"),
                            (3, "Very satisfied"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "security_confidence",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Moderate"), (3, "High")], default=2
                    ),
                ),
                ("future_expectations", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="sd", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contactno",
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(default="sd", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(default="Sd", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(default="sd", max_length=100),
        ),
    ]
