# Generated by Django 4.2.7 on 2023-11-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CryptoWebsite",
            "0011_feedback_userprofile_city_userprofile_contactno_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.TextField(default="sd", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="contactno",
            field=models.TextField(default=123),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.TextField(default="sd", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.TextField(default="Sd", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="lastname",
            field=models.TextField(default="sd", max_length=100),
        ),
    ]
